### ISSUE TITLE
Add method for getting all project files as a stream

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-compiler#10]
Followup: https://github.com/ckeditor/ckeditor5-dev-utils/issues/11

**Comment by pomek** [comment]
See: https://github.com/ckeditor/ckeditor5-dev-builder/pull/11#issuecomment-238025301

**Comment by Reinmar** [comment]
See https://github.com/ckeditor/ckeditor5-dev-compiler/pull/11#issuecomment-240664765. Compiler should export its utils so other packages can use them. Otherwise, we'll be slowly and painfully moving all its utils to the utils package.

**Comment by Reinmar** [comment]
Do I understand correctly that this isn't a method for collecting all sample files but generally all project files, right?

**Comment by pomek** [comment]
Exactly. We can specify which files we would like to collect.
