### ISSUE TITLE
Add --es5 option to create a ES5 compatible compilations

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-compiler#18]
Needed for https://github.com/ckeditor/ckeditor5/issues/201.

**Comment by oskarwrobel** [comment]
We should consider to use: https://babeljs.io/docs/plugins/external-helpers/

> Babel has a few helper functions that’ll be placed at the top of the generated code if needed so it’s not inlined multiple times throughout that file. This may become an issue if you have multiple files, especially when you’re sending them to the browser. gzip alleviates most of this concern but it’s still not ideal.

**Comment by Reinmar** [comment]
I made a small change in a static file used by Bender (https://github.com/ckeditor/ckeditor5/commit/894eb184150ccffcf69aadab5f4713587576e1c1) which makes Safari parse this.

**Comment by maxbarnas** [comment]
I pushed commit on `t/18` with list of plugins, that was taken from `babel-preset-es2015` preset. Direct use of that preset was limited because of the known problem with relative paths.

To make this code work you also have to prepend path `node_modules/babel-polyfill/dist/polyfill.js` to polyfill in `ckeditor5/bender.js`:

```js
...
applications: {
		ckeditor: {
			path: '.',
			files: [
				'node_modules/babel-polyfill/dist/polyfill.js',
				'node_modules/requirejs/require.js'
			],
			basePath: '/apps/ckeditor/build/modules/amd/'
		}
	},
...
```

Install polyfill in `ckeditor5` repo with `npm install babel-polyfill`.

All that helps just with removing generator functions from code. ~~Safari still isn't working after this treatment. It has some problems with paths to test code.~~

Over 100 tests in Chrome also break after this. At least some of them are occurring because of `babel-plugin-transform-es2015-classes` plugin. 

Example of failed test log message:
```
tests.js:1036 Test failed in: build: modules/amd/tests/core/editor/editor-base 
Name: should throw an error if specified command has not been added

AssertionError: expected [Function] to throw 'CKEditorError' but 'CKEditorError: editor-command-not-found: Specified command has not been added to the editor.' was thrown
    at Context.<anonymous> (http://localhost:1030/build/modules/amd/tests/core/editor/editor-base:126:16)
```

**Comment by Reinmar** [comment]
And I pushed https://github.com/ckeditor/ckeditor5-dev-compiler/tree/t/18b enabling ES5 compilation.

Now I could check quickly on Safari that couple tests are failing. I identified at least two cases – the case with `CKEditorErorr` matching, that @maxbarnas mentioned above. And lack of `regeneratorRuntime`.

**Comment by Reinmar** [comment]
I also pushed https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-dev-compiler/18 which enables Babel polyfill. Now, nearly only tests which check `CKEditorError` fails.

**Comment by Reinmar** [comment]
Some more failing tests on Safari, other than CKEError related:

* http://tests.ckeditor.dev:1030/build/modules/amd/tests/engine/model/composer/modifyselection
* http://tests.ckeditor.dev:1030/build/modules/amd/tests/engine/view/document/jumpoverinlinefiller
* http://tests.ckeditor.dev:1030/build/modules/amd/tests/ui/template (one in the middle)

**Comment by Reinmar** [comment]
The problem with errors is that unfortunately you cannot throw a child class of `Error` ;/

We've been planning to extend `expect.to.throw()` to check for `CKEditorError` anyway, so this may need to be done now to fix all those tests.

**Comment by Reinmar** [comment]
But it's super strange that you get the same error on Chrome on which not transpiled tests work. Most likely, Babel isn't transpiling classes inheriting from `Error` in a normal way...

**Comment by maxbarnas** [comment]
Yep, same idea here. Plugin `babel-plugin-transform-es2015-classes` brakes something while transforming code.

**Comment by Reinmar** [comment]
That's the ticket about checking `CKEditorError`: https://github.com/ckeditor/ckeditor5-utils/issues/2.

OTOH, I'm afraid that such a code may break if we try to use `instanceof CKEditorError` somewhere in our code (outside tests). We won't be able to do so because this is not going to work when transpiled. But it seems that this will be caught by tests anyway, because such code simply won't work.

**Comment by Reinmar** [comment]
I can also see that there should be some other solution: http://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node – we could use https://www.npmjs.com/package/babel-plugin-transform-builtin-extend. I've looked into the code and I think that it will be safer to avoid using this extension.

**Comment by Reinmar** [comment]
I was thinking how we could implement `isCKEditorError` so it works with those transpiled errors. I saw that the class name was moved to the error message, which fortunately lets use create a pretty safe check:

```js
export function isCKEditorError( error, messagePattern ) {
    if ( error instanceof CKEditorError || error.message.startsWith( 'CKEditorError: ' ) ) {
        // .... 
    }
}
```

Hopefully, this will work on all browsers.
