### ISSUE TITLE
Compiler entry point

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-dev-compiler#25]
I should be able to compile CKEditor with a Node function. Now I need to understand this piece of code https://github.com/ckeditor/ckeditor5/blob/master/gulpfile.js#L77-L110 to know what to do to compile CKEditor.

**Comment by Reinmar** [comment]
This is strongly related to https://github.com/ckeditor/ckeditor5/issues/308.

Every package like the compiler should expose functions which use `runSequence()` or different util to combine needed deps into a one stream that can be used to create the entry-point with a single line of code. This will also allow avoiding creating tasks like `gulp clean:*` or the `*:esnext` set.

**Comment by Reinmar** [comment]
Fixed by #43.
