### ISSUE TITLE
Separation between config and options looks weird

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-dev-compiler#29]
I understand that config is fixed and option is something you can change via command line, but at the end of the day, when you want to simply call the function separation looks weird:

```js
const ckeditorCompilerConfig = {
	ROOT_DIR: '.',
	WORKSPACE_DIR: '..',
	MODULE_DIR: {
		amd: 'lib/ckeditor',
		cjs: 'lib/ckeditor',
		esnext: 'lib/ckeditor'
	}
};

const ckeditorCompilerOptions = {
	formats: [ 'esnext' ],
	watch: false
};

require( '@ckeditor/ckeditor5-dev-compiler' )( ckeditorCompilerConfig ).compiler.compile.js( ckeditorCompilerOptions );

```

**Comment by pjasiun** [comment]
I think all of them should be passed directly to the function, not as a global to the package.

**Comment by pomek** [comment]
@pjasiun, we did a few changes in API. Is this ticket still valid?

**Comment by Reinmar** [comment]
While this issue is solved in this repo, it's still present in other packages. So we could close it here, but please report similar issues in other packages which expect the config.
