### ISSUE TITLE
Get rid of the PhantomJS dependency for compiling SVG sprites

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-dev-compiler#38]
At this moment the compiler uses [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite), which in turn uses svg-sprite, which requires PhantomJS to work. 

I used that particular gulp task because at that time it seemed to be the fastest way to bootstrap the builder but now it feels like an overkill. Why? PJS is super–heavy and takes a lot of time to download. In fact, we don't even use [that part of svg-sprite](https://github.com/jkphl/svg-sprite/issues/100#issuecomment-125572326), which requires PJS at all. It would be nice to get rid of it at some point.

The first hit in google is https://github.com/w0rm/gulp-svgstore, which seems to be free of super–heavy dependencies. We'd only need to figure out how to obtain a pure svg _string_ at the end of the pipe instead of svg file, so it can [fill the iconmanagermodel](https://github.com/ckeditor/ckeditor5-dev-compiler/blob/master/lib/compiler/iconmanagermodel.tpl) somehow.

**Comment by httpete** [comment]
ya, I can't get PhantomJs inside my VED. I don't even think we need it to use svg-sprite just to compile. +1

**Comment by Reinmar** [comment]
This package is not used by CKEditor 5 anymore. As this repo's title says – it was merged to https://github.com/ckeditor/ckeditor5-dev but, most importantly, we switched to Webpack so it handles SVGs at the moment. 

How did you find this ticket, @httpete? :)
