### ISSUE TITLE
Compiler always requires DOCUMENTATION.SAMPLES config

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev-compiler#41]
When using compiler for 3rd party projects, developer should not care about configuration related with documentation samples. This option is needed now and compiler throws error when it is not provided.

**Comment by pomek** [comment]
Related ticket: https://github.com/ckeditor/ckeditor5-dev-compiler/issues/15

I have the same feelings. From an external project point of view, we want to compile only the CKEditor5 sources. Nothing more.

**Comment by Reinmar** [comment]
We've been saying in general that the config options should be passed directly to the specific task methods, not to the whole module. I also pointed this out during the latest change's review, exactly for this reason, but we forgot to create a specific followup ticket for this issue.

Anyway, that's the expected solution. Anything else now will be just a waste of time.

**Comment by Reinmar** [comment]
Fixed by #43.
