### ISSUE TITLE
Various improvements for integrating CKEditor into other projects

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-compiler#42]
- [x] Load CKEditor packages from configurable locations. Currently, all packages must be in `node_modules/`. It'd be great if you could define in the compiler where to look for a package.
- [x] The output path (where compiler puts the build) should be configurable. Theoretically, this is doable now, but it's buggy – https://github.com/ckeditor/ckeditor5-dev-compiler/issues/30, https://github.com/ckeditor/ckeditor5-dev-compiler/issues/26, https://github.com/ckeditor/ckeditor5-dev-compiler/issues/41 and perhaps even more.
- [x] The compiler package should expose a single, simple task so you can keep your `gulpfile.js` short. It could also expose a bash script so the developer wouldn't need Gulp at all. See https://github.com/ckeditor/ckeditor5-dev-compiler/issues/25.

**Comment by pjasiun** [comment]
The last point is reported separately here: https://github.com/ckeditor/ckeditor5-dev-compiler/issues/25

**Comment by pjasiun** [comment]
But I think it should be a node script (no gulp needed but keep it in the JavaScript).
