### ISSUE TITLE
Add -w alias for the compiler's --watch option

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-compiler#55]
To match the test task's options.

Make sure to update the docs (https://github.com/ckeditor/ckeditor5/wiki/Development-Environment).

**Comment by Reinmar** [comment]
We can also add `-f` option for `--formats` and/or change the default of `--formats` to `esnext` since from this moment we won't be using AMD anywhere.

**Comment by pomek** [comment]
Sure.
